export const config = Object.freeze({
    embedColor: 0x1DB954,
    errorColor: 0xFF4444,
    emojis: {
        play: '\u25B6\uFE0F',
        pause: '\u23F8\uFE0F',
        stop: '\u23F9\uFE0F',
        skip: '\u23ED\uFE0F',
        queue: '\uD83D\uDCDC',
        loop: '\uD83D\uDD01',
        loopQueue: '\uD83D\uDD03',
        shuffle: '\uD83D\uDD00',
        music: '\uD83C\uDFB5',
        volume: '\uD83D\uDD0A',
        disconnect: '\uD83D\uDC4B',
        nowPlaying: '\uD83C\uDFB6',
    },
    maxQueryLength: 300,
    maxReasonLength: 512,
    ownerIds: process.env.OWNER_IDS?.split(',').map(s => s.trim()) || [],
    voteSkipPercent: 0.5,
    defaultVolume: 80,
    maxVolume: 150,
    progressBarLength: 15,
});